### ISSUE TITLE
Open Source 

### ISSUE THREAD

**Issue by slyapustin** [jumpingrivers/diffify#6]
The project looks nice, do you have any plans to make it open source?

**Comment by csgillespie** [comment]
We still changing the backend a lot. Over the last month, the website has remained stable, but the backend has had major changes as we start thinking about Python, dev pkg versions, and other repos. Also, the set-up has been optimised for our particular set-up.

In the near future, we'll have an API that people can use. 

After that, we'll think about what to make open-source.

Thanks for your interest!
